### ISSUE TITLE
Possible regression in 5.4.0 - no mail notification received

### ISSUE THREAD

**Issue by mchubby** [MyCollab/mycollab#16]
**Steps to reproduce**

- Build install zip from maven (community)
- backup&delete old directory and unzip distribution
- carry over old .properties config
- Login and create/update task

**Expected result**

Mail notification to observers

**Observed result**

No mail received.

Stacktrace in mycollab.out:

```
13:44:00,135 ERROR c.m.s.j.ProjectSendingRelayEmailNotificationJob:50 - Error while sending scheduler command
freemarker.core._MiscTemplateException: When calling macro "commentBlock", required parameter "avatar" (parameter #1) was specified, but had null/missing value.

----
Tip: If the parameter value expression on the caller side is known to be legally null/missing, you may want to specify a default value for it with the "!" operator, like paramValue!defaultValue.
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: #macro commentBlock avatar displayNam...  [in template "macroTextBlock.ftl" in macro "commentBlock" at line 18, column 1]
        - Reached through: @lib.commentBlock avatar=commentItem...  [in template "mailProjectItemCommentNotifier.ftl" at line 22, column 17]
----
        at freemarker.core.Macro$Context.sanityCheck(Macro.java:219)
        at freemarker.core.Environment.invoke(Environment.java:714)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
        at freemarker.core.Environment.visit(Environment.java:363)
        at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:316)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:272)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:243)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:596)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
        at freemarker.core.Environment.visit(Environment.java:327)
        at freemarker.core.Environment.visit(Environment.java:333)
        at freemarker.core.Environment.visit(Environment.java:333)
        at freemarker.core.Environment.process(Environment.java:306)
        at freemarker.template.Template.process(Template.java:384)
        at com.mycollab.module.mail.service.ContentGenerator.parseFile(ContentGenerator.scala:61)
        at com.mycollab.module.project.schedule.email.service.SendMailToFollowersAction$$anonfun$sendNotificationForCommentAction$1.apply(SendMailToFollowersAction.scala:132)
        at com.mycollab.module.project.schedule.email.service.SendMailToFollowersAction$$anonfun$sendNotificationForCommentAction$1.apply(SendMailToFollowersAction.scala:123)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at com.mycollab.module.project.schedule.email.service.SendMailToFollowersAction.sendNotificationForCommentAction(SendMailToFollowersAction.scala:123)
        at com.mycollab.schedule.jobs.ProjectSendingRelayEmailNotificationJob$$anonfun$executeJob$1.apply(ProjectSendingRelayEmailNotificationJob.scala:58)
        at com.mycollab.schedule.jobs.ProjectSendingRelayEmailNotificationJob$$anonfun$executeJob$1.apply(ProjectSendingRelayEmailNotificationJob.scala:49)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at com.mycollab.schedule.jobs.ProjectSendingRelayEmailNotificationJob.executeJob(ProjectSendingRelayEmailNotificationJob.scala:49)
        at com.mycollab.schedule.jobs.GenericQuartzJobBean.executeInternal(GenericQuartzJobBean.scala:34)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

Edit: package has freemarker-gae-2.3.25-incubating.jar

**Comment by mchubby** [comment]
Update : Please mark this bug as invalid
I had hotpatched setting user SMTP credentials to allow sending mail on open relay, but (#15) disallows such blank settings (INFO c.m.m.m.NullMailer:45 - You did not configure email. So Email feature is disable and MyCollab can not send any notification via email.
).

**Comment by haiphucnguyen** [comment]
Thank you for the clear input. Have a nice weekend
