### ISSUE TITLE
Unable to setup MyCollab

### ISSUE THREAD

**Issue by mhermosi** [MyCollab/mycollab#19]
Hi,
I'm having the following issue on latest version: After configure MyCollab from the web interface, Jetty is not able to start the app.:

01:12:37,313  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-mobile-5.4.3.jar
01:12:37,313  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-migration-5.4.3.jar
01:12:37,314  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-scheduler-community-5.4.3.jar
01:12:37,314  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-ui-5.4.3.jar
01:12:37,315  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-esb-5.4.3.jar
01:12:37,315  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-app-community-5.4.3.jar
01:12:37,316  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-scheduler-5.4.3.jar
01:12:37,321  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-config-5.4.3.jar
01:12:37,325  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-core-5.4.3.jar
01:12:37,325  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-servlet-5.4.3.jar
01:12:37,326  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-services-5.4.3.jar
01:12:37,326  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-server-runner-5.4.3.jar
01:12:37,327  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-jackrabbit-5.4.3.jar
01:12:37,327  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-web-community-5.4.3.jar
01:12:37,328  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-reporting-5.4.3.jar
01:12:37,336  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-services-community-5.4.3.jar
01:12:37,337  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-web-5.4.3.jar
01:12:37,337  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-dao-5.4.3.jar
01:12:37,338  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-caching-5.4.3.jar
01:12:37,338  INFO c.m.s.JettyServerBasedRunner:261 - Load jar file to classpath /mnt/java/mycollab/lib/mycollab-localization-5.4.3.jar
01:12:37,339  INFO c.m.s.JettyServerBasedRunner:279 - Init the datasource
01:12:37,453  WARN o.e.j.w.WebAppContext:529 - Failed startup of context o.e.j.w.WebAppContext@677d2924{/,file:///mnt/java/mycollab/webapp/,null}{/mnt/java/mycollab/webapp}
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:409)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:326)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:143)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:94)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:483)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:519)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.mycollab.server.JettyServerBasedRunner$ServerLifeCycleListener.lambda$lifeCycleStarted$2(JettyServerBasedRunner.java:325)
	at java.lang.Thread.run(Thread.java:745)
01:12:37,458  INFO o.e.j.s.h.ContextHandler:781 - Started o.e.j.s.ServletContextHandler@75afeca0{/it,null,AVAILABLE}
01:12:37,465  INFO o.e.j.s.h.ContextHandler:910 - Stopped o.e.j.s.ServletContextHandler@4bbfb90a{/,null,UNAVAILABLE}

Thanks,

-Martin

**Comment by haiphucnguyen** [comment]
It seems you download the zip file not completely. You should download the distribution again then see if the problem is persisted.

Regards,
Hai

**Comment by mhermosi** [comment]
ok thanks

**Comment by mhermosi** [comment]
Thanks... that was odd. but indeed re-downloading the zip file worked.

**Comment by haiphucnguyen** [comment]
Glad to see it works :). In the next release, we will add checksum in the zip file to avoid this issue.
