### ISSUE TITLE
exec startup.sh script after ,the soft is Exception

### ISSUE THREAD

**Issue by huangmeng4520** [MyCollab/mycollab#24]
main] INFO com.esofthead.mycollab.Executor - Load config variables at /opt/MyCollab-5.3.4/bin/mycollab.ini--true
[main] INFO com.esofthead.mycollab.Executor - Options in config file: -server -Xms128m -Xmx768m -XX:MaxPermSize=256m -XX:+DisableExplicitGC -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC
[main] INFO com.esofthead.mycollab.Executor - Start MyCollab server process
Exception in thread "main" java.net.BindException: Address already in use
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:375)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at java.net.ServerSocket.<init>(ServerSocket.java:128)
        at com.esofthead.mycollab.Executor.runServer(Executor.java:122)
        at com.esofthead.mycollab.Executor.main(Executor.java:213)

**Comment by haiphucnguyen** [comment]
Exception in thread "main" java.net.BindException: Address already in use

The default port 8080 is being used. You can change the port value [here](https://community.mycollab.com/docs/hosting-mycollab-on-your-own-server/frequently-questions-and-answers/#defaultport)
