### ISSUE TITLE
Running startup.sh fails with exception on ubuntu 14 with default-jdk

### ISSUE THREAD

**Issue by ehthisham** [MyCollab/mycollab#7]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/j
etty/util/component/LifeCycle$Listener : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.getMethod0(Class.java:2856)
        at java.lang.Class.getMethod(Class.java:1668)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)

**Comment by haiphucnguyen** [comment]
Thanks for reporting. As we discussed in this thread http://support.mycollab.com/topic/798110-redirecting-to-the-wrong-page-after-database-configuration-and-email-configuration-page/, we use Jetty 9.3 and it requires Java 8. The next version MyCollab 5.1.0, which is released in this weekend will fix this issue

**Comment by ehthisham** [comment]
Wow  that fast! Thank you :)

**Comment by haiphucnguyen** [comment]
This issue is resolved. We tested on the JRE 7 and it works well. You can get it run with IntelliJ or wait for us to create an installer. Thanks for reporting again.
